### ISSUE TITLE
Fix warnings using mockito in the unit tests 

### ISSUE THREAD

**Issue by alejouribesanchez** [veryfi/veryfi-java#14]
There are some warnings related to the lines

`HttpResponse<String> httpResponse = mock(HttpResponse.class);`

`when(httpClient.send(any(HttpRequest.class), any(HttpResponse.BodyHandler.class))).thenReturn(httpResponse);`

<img width="891" alt="Screen Shot 2021-08-10 at 4 09 54 PM" src="https://user-images.githubusercontent.com/3950665/128935630-d81e3d9e-8170-440a-af31-606911712ccd.png">

Find a way to avoid these warnings

**Comment by AsadShakeel** [comment]
The first warning can't be resolved as [the feature is requested in the Mockito to mock generics.](https://github.com/mockito/mockito/issues/1531). The warning can be removed using specific libraries such as mentioned in the same issue.

However, the second warning is resolved in the PR https://github.com/veryfi/veryfi-java/pull/24 using [this StackOverflow answer](https://stackoverflow.com/a/13932751/4539906).
